auto_voice_channel_names = ['Silence',
                            'Iron Victory',
                            'Leviathan',
                            'Kraken\'s Kiss',
                            'Reaper\'s Wind',
                            'Black Wind',
                            'Sea Bitch',
                            'Silence',
                            'Noble Lady',
                            'Red God\'s Wrath',
                            'Shrike',
                            'Shade',
                            'Ghost',
                            'Slaver\'s Scream',
                            'Sea Song',
                            'Thunderer',
                            'Nighflyer',
                            'Silverfin',
                            'Black Wind',
                            'Great Kraken']
